/**
 * @file collision-blobs.test.ts
 *
 * Test loading collision data from blob files generated by npm scripts.
 */

import { readFileSync } from 'fs'
import { join } from 'path'
import { DDCOLLISION_BLOB_URL } from '../../src/set-by-build'
import { randomDDIndex } from '../test-util'
import { ok } from 'assert'
import { Lut } from '../../src/simulation/luts/lut'

describe('collision data blobs in public/luts', function () {
  it('loads as valid disk-disk -> bounce tree', function () {
    const blobPath = join(__dirname, `../../public/${DDCOLLISION_BLOB_URL}`)
    const readBuffer = readFileSync(blobPath)
    const blobData = new Int16Array(
      readBuffer.buffer, readBuffer.byteOffset,
      readBuffer.byteLength / Int16Array.BYTES_PER_ELEMENT)

    ok(typeof blobData[0] === 'number'
      && (blobData[0] === Math.floor(blobData[0])),
    'blobData values should be integers')

    const lut = Lut.create('disk-disk-lut')
    lut.loadFromBlob(blobData)

    // Compare random indices before and after
    const randomIndices = Array.from({ length: 100 }).map(() => randomDDIndex())

    for (const [dxi, dyi, vxi, vyi] of randomIndices) {
      // const bounce = DiskDiskCollisions.cache[dxi][dyi][vxi][vyi]
      const bounce = lut.tree[dxi][dyi][vxi][vyi]
      if (bounce !== null) {
        ok(typeof bounce[0] === 'number'
          && (bounce[0] === Math.floor(bounce[0])),
        'bounce values should be integers')
      }
    }
  })
})
