/**
 * @file lut-blobs.testSKIP.ts
 *
 * Test loading lut data from blob files generated by npm scripts.
 */

import { readFileSync } from 'fs'
import { join } from 'path'
import { lookupIndex, lutSpecs } from '../test-util'
import { ok } from 'assert'
import { Lut } from '../../src/simulation/luts/lut'

for (const { lutName, shapeName, blobUrl, indexer } of lutSpecs) {
  describe(`${lutName} data blob in public`, function () {
    it('loads as valid tree', function () {
      const blobPath = join(__dirname, `../../public/${blobUrl}`)
      const readBuffer = readFileSync(blobPath)
      const blobData = new Int16Array(
        readBuffer.buffer, readBuffer.byteOffset,
        readBuffer.byteLength / Int16Array.BYTES_PER_ELEMENT)

      ok(typeof blobData[0] === 'number'
        && (blobData[0] === Math.floor(blobData[0])),
      'blobData values should be integers')

      const lut = Lut.create(lutName, shapeName)
      lut.loadFromBlob(blobData)

      // Compare random indices before and after
      const randomIndices = Array.from({ length: 100 }).map(indexer)

      for (const index of randomIndices) {
      // const bounce = DiskDiskCollisions.cache[dxi][dyi][vxi][vyi]
        const leaf = lookupIndex(lut.tree, index)
        if (leaf !== null) {
          ok(leaf.every(val =>
            typeof val === 'number'
            && (val === Math.floor(val)),
          ),
          `leaf values should be integers: ${JSON.stringify(index)} -> ${JSON.stringify(leaf)}`)
        }
      }
    })
  })
}
