/**
 * @file lut-blobs.test.ts
 *
 * Test loading lut data from blob files generated by npm scripts.
 */

import { readFileSync } from 'fs'
import { join } from 'path'
import { DISK_DISK_LUT_BLOB_URL } from '../../src/set-by-build'
import { randomDiskDiskIndex } from '../test-util'
import { ok } from 'assert'
import { Lut } from '../../src/simulation/luts/lut'
import { LutName } from '../../src/imp-names'

type Spec = {
  lutName: LutName
  blobUrl: string
  indexer: () => Array<number>
}

const specs = [
  {
    lutName: 'disk-disk-lut',
    blobUrl: DISK_DISK_LUT_BLOB_URL,
    indexer: randomDiskDiskIndex,
  },
] as const satisfies Array<Spec>

for (const { lutName, blobUrl, indexer } of specs) {
  describe(`${lutName} data blob in public`, function () {
    it('loads as valid disk-disk -> bounce tree', function () {
      const blobPath = join(__dirname, `../../public/${blobUrl}`)
      const readBuffer = readFileSync(blobPath)
      const blobData = new Int16Array(
        readBuffer.buffer, readBuffer.byteOffset,
        readBuffer.byteLength / Int16Array.BYTES_PER_ELEMENT)

      ok(typeof blobData[0] === 'number'
        && (blobData[0] === Math.floor(blobData[0])),
      'blobData values should be integers')

      const lut = Lut.create(lutName)
      lut.loadFromBlob(blobData)

      // Compare random indices before and after
      const randomIndices = Array.from({ length: 100 }).map(indexer)

      for (const [dxi, dyi, vxi, vyi] of randomIndices) {
      // const bounce = DiskDiskCollisions.cache[dxi][dyi][vxi][vyi]
        const leaf = lut.tree[dxi][dyi][vxi][vyi]
        if (leaf !== null) {
          ok(typeof leaf[0] === 'number'
            && (leaf[0] === Math.floor(leaf[0])),
          'leaf values should be integers')
        }
      }
    })
  })
}
